# Generated by Django 5.2.17 on 2026-08-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
