# Generated by Django 5.2.17 on 2026-08-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_resumeanalysis_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='sections',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
