# Generated by Django 5.2.17 on 2026-08-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_builtresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtresume',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic ATS'), ('modern', 'Modern ATS'), ('student', 'Student / Fresher ATS'), ('professional', 'Professional ATS'), ('executive', 'Executive ATS'), ('minimal', 'Minimal ATS')], default='classic', max_length=20),
        ),
    ]
